require('plugins')
require('settings.general')
require('keys.keybindings')
require('user-plugins.TreeSitter.treesitter')
require('user-plugins.NvimTree.nvimtree')
require('user-plugins.Cmp.cmp')
require('user-plugins.Dashboard.dashboard')
require('user-plugins.Telescope.telescope')
